omap: fix compile error in emif-common.c
ext_phy_ctrl_const_base is currently only defined if
CONFIG_SYS_EMIF_PRECALCULATED_TIMING_REGS is set.

If not set, the following error occurs:

In function `do_sdram_init':
| arch/arm/cpu/armv7/omap-common/emif-common.c:985: undefined reference to `ext_phy_ctrl_const_base'

Signed-off-by: Steve Sakoman <steve@sakoman.com>